
/**
 * @ingroup data_pool
 * 
 * @file DataPool_generated.c
 * @author Generated by DataPool_generate.py
 * @brief Generated code to assist with DataPool usage.
 * 
 * This file was generated from DataPool_struct.h by DataPool_generate.py.
 * 
 * @version Generated from DataPool_struct.h version 0.1
 * @date 2021-02-23
 * 
 * @copyright Copyright (c) UoS3 2020
 */

/* -------------------------------------------------------------------------   
 * INCLUDES
 * ------------------------------------------------------------------------- */

/* Standard library includes */
#include <stddef.h>

/* Internal includes */
#include "util/debug/Debug_public.h"
#include "system/data_pool/DataPool_public.h"
#include "system/data_pool/DataPool_generated.h"

/* -------------------------------------------------------------------------   
 * FUNCTIONS
 * ------------------------------------------------------------------------- */

bool DataPool_get(
    DataPool_Id id_in,
    void **pp_data_out,
    DataPool_DataType *p_data_type_out,
    size_t *p_data_size_out
) {

    switch (id_in) {
    
    
    /* DP.INITIALISED */
    case 0x0001:
        *pp_data_out = &DP.INITIALISED;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.BOARD_INITIALISED */
    case 0x0002:
        *pp_data_out = &DP.BOARD_INITIALISED;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.EVENTMANAGER.INITIALISED */
    case 0x0c01:
        *pp_data_out = &DP.EVENTMANAGER.INITIALISED;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.EVENTMANAGER.ERROR_CODE */
    case 0x0c02:
        *pp_data_out = &DP.EVENTMANAGER.ERROR_CODE;
        *p_data_type_out = DATAPOOL_DATATYPE_ERRORCODE;
        *p_data_size_out = sizeof(ErrorCode);
        return true;


    /* DP.EVENTMANAGER.MAX_EVENTS_REACHED */
    case 0x0c03:
        *pp_data_out = &DP.EVENTMANAGER.MAX_EVENTS_REACHED;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.EVENTMANAGER.NUM_RAISED_EVENTS */
    case 0x0c04:
        *pp_data_out = &DP.EVENTMANAGER.NUM_RAISED_EVENTS;
        *p_data_type_out = DATAPOOL_DATATYPE_UINT8_T;
        *p_data_size_out = sizeof(uint8_t);
        return true;


    /* DP.EVENTMANAGER.EVENT_LIST_SIZE */
    case 0x0c05:
        *pp_data_out = &DP.EVENTMANAGER.EVENT_LIST_SIZE;
        *p_data_type_out = DATAPOOL_DATATYPE_SIZE_T;
        *p_data_size_out = sizeof(size_t);
        return true;


    /* DP.IMU.INITIALISED */
    case 0x9401:
        *pp_data_out = &DP.IMU.INITIALISED;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.IMU.ERROR_CODE */
    case 0x9402:
        *pp_data_out = &DP.IMU.ERROR_CODE;
        *p_data_type_out = DATAPOOL_DATATYPE_ERRORCODE;
        *p_data_size_out = sizeof(ErrorCode);
        return true;


    /* DP.IMU.I2C_ERROR_CODE */
    case 0x9403:
        *pp_data_out = &DP.IMU.I2C_ERROR_CODE;
        *p_data_type_out = DATAPOOL_DATATYPE_ERRORCODE;
        *p_data_size_out = sizeof(ErrorCode);
        return true;


    /* DP.IMU.STATE */
    case 0x9404:
        *pp_data_out = &DP.IMU.STATE;
        *p_data_type_out = DATAPOOL_DATATYPE_IMU_STATE;
        *p_data_size_out = sizeof(Imu_State);
        return true;


    /* DP.IMU.SUBSTATE */
    case 0x9405:
        *pp_data_out = &DP.IMU.SUBSTATE;
        *p_data_type_out = DATAPOOL_DATATYPE_IMU_SUBSTATE;
        *p_data_size_out = sizeof(Imu_SubState);
        return true;


    /* DP.IMU.COMMAND */
    case 0x9406:
        *pp_data_out = &DP.IMU.COMMAND;
        *p_data_type_out = DATAPOOL_DATATYPE_IMU_COMMAND;
        *p_data_size_out = sizeof(Imu_Command);
        return true;


    /* DP.IMU.GYROSCOPE_DATA */
    case 0x9407:
        *pp_data_out = &DP.IMU.GYROSCOPE_DATA;
        *p_data_type_out = DATAPOOL_DATATYPE_IMU_VECINT16;
        *p_data_size_out = sizeof(Imu_VecInt16);
        return true;


    /* DP.IMU.GYROSCOPE_DATA_VALID */
    case 0x9408:
        *pp_data_out = &DP.IMU.GYROSCOPE_DATA_VALID;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.IMU.MAGNETOMETER_DATA */
    case 0x9409:
        *pp_data_out = &DP.IMU.MAGNETOMETER_DATA;
        *p_data_type_out = DATAPOOL_DATATYPE_IMU_VECINT16;
        *p_data_size_out = sizeof(Imu_VecInt16);
        return true;


    /* DP.IMU.MAGNE_SENSE_ADJUST_DATA */
    case 0x940a:
        *pp_data_out = &DP.IMU.MAGNE_SENSE_ADJUST_DATA;
        *p_data_type_out = DATAPOOL_DATATYPE_IMU_VECUINT8;
        *p_data_size_out = sizeof(Imu_VecUint8);
        return true;


    /* DP.IMU.MAGNETOMETER_DATA_VALID */
    case 0x940b:
        *pp_data_out = &DP.IMU.MAGNETOMETER_DATA_VALID;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.IMU.TEMPERATURE_DATA */
    case 0x940c:
        *pp_data_out = &DP.IMU.TEMPERATURE_DATA;
        *p_data_type_out = DATAPOOL_DATATYPE_INT16_T;
        *p_data_size_out = sizeof(int16_t);
        return true;


    /* DP.IMU.TEMPERATURE_DATA_VALID */
    case 0x940d:
        *pp_data_out = &DP.IMU.TEMPERATURE_DATA_VALID;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.MEMSTOREMANAGER.ERROR_CODE */
    case 0x1001:
        *pp_data_out = &DP.MEMSTOREMANAGER.ERROR_CODE;
        *p_data_type_out = DATAPOOL_DATATYPE_ERRORCODE;
        *p_data_size_out = sizeof(ErrorCode);
        return true;


    /* DP.MEMSTOREMANAGER.EEPROM_ERROR_CODE */
    case 0x1002:
        *pp_data_out = &DP.MEMSTOREMANAGER.EEPROM_ERROR_CODE;
        *p_data_type_out = DATAPOOL_DATATYPE_ERRORCODE;
        *p_data_size_out = sizeof(ErrorCode);
        return true;


    /* DP.MEMSTOREMANAGER.CFG_FILE_1_OK */
    case 0x1003:
        *pp_data_out = &DP.MEMSTOREMANAGER.CFG_FILE_1_OK;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.MEMSTOREMANAGER.CFG_FILE_2_OK */
    case 0x1004:
        *pp_data_out = &DP.MEMSTOREMANAGER.CFG_FILE_2_OK;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.MEMSTOREMANAGER.CFG_FILE_3_OK */
    case 0x1005:
        *pp_data_out = &DP.MEMSTOREMANAGER.CFG_FILE_3_OK;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.EPS.INITIALISED */
    case 0x8801:
        *pp_data_out = &DP.EPS.INITIALISED;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.EPS.ERROR_CODE */
    case 0x8802:
        *pp_data_out = &DP.EPS.ERROR_CODE;
        *p_data_type_out = DATAPOOL_DATATYPE_ERRORCODE;
        *p_data_size_out = sizeof(ErrorCode);
        return true;


    /* DP.EPS.STATE */
    case 0x8803:
        *pp_data_out = &DP.EPS.STATE;
        *p_data_type_out = DATAPOOL_DATATYPE_EPS_STATE;
        *p_data_size_out = sizeof(Eps_State);
        return true;


    /* DP.EPS.CONFIG_SYNCED */
    case 0x8804:
        *pp_data_out = &DP.EPS.CONFIG_SYNCED;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.EPS.NEW_REQUEST */
    case 0x8805:
        *pp_data_out = &DP.EPS.NEW_REQUEST;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.EPS.EPS_REQUEST[EPS_MAX_UART_FRAME_LENGTH] */
    case 0x8806:
        *pp_data_out = &DP.EPS.EPS_REQUEST[EPS_MAX_UART_FRAME_LENGTH];
        *p_data_type_out = DATAPOOL_DATATYPE_UINT8_T;
        *p_data_size_out = sizeof(uint8_t);
        return true;


    /* DP.EPS.EPS_REQUEST_LENGTH */
    case 0x8807:
        *pp_data_out = &DP.EPS.EPS_REQUEST_LENGTH;
        *p_data_type_out = DATAPOOL_DATATYPE_SIZE_T;
        *p_data_size_out = sizeof(size_t);
        return true;


    /* DP.EPS.EPS_REPLY[EPS_MAX_UART_FRAME_LENGTH] */
    case 0x8808:
        *pp_data_out = &DP.EPS.EPS_REPLY[EPS_MAX_UART_FRAME_LENGTH];
        *p_data_type_out = DATAPOOL_DATATYPE_UINT8_T;
        *p_data_size_out = sizeof(uint8_t);
        return true;


    /* DP.EPS.EPS_REPLY_LENGTH */
    case 0x8809:
        *pp_data_out = &DP.EPS.EPS_REPLY_LENGTH;
        *p_data_type_out = DATAPOOL_DATATYPE_SIZE_T;
        *p_data_size_out = sizeof(size_t);
        return true;


    /* DP.EPS.UART_FRAME_NUMBER */
    case 0x880a:
        *pp_data_out = &DP.EPS.UART_FRAME_NUMBER;
        *p_data_type_out = DATAPOOL_DATATYPE_UINT8_T;
        *p_data_size_out = sizeof(uint8_t);
        return true;


    /* DP.EPS.COMMAND_STATUS */
    case 0x880b:
        *pp_data_out = &DP.EPS.COMMAND_STATUS;
        *p_data_type_out = DATAPOOL_DATATYPE_EPS_COMMANDSTATUS;
        *p_data_size_out = sizeof(Eps_CommandStatus);
        return true;


    /* DP.EPS.HK_DATA */
    case 0x880c:
        *pp_data_out = &DP.EPS.HK_DATA;
        *p_data_type_out = DATAPOOL_DATATYPE_EPS_HKDATA;
        *p_data_size_out = sizeof(Eps_HkData);
        return true;


    /* DP.MISSION.INITIALISED */
    case 0xd001:
        *pp_data_out = &DP.MISSION.INITIALISED;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.MISSION.ERROR_CODE */
    case 0xd002:
        *pp_data_out = &DP.MISSION.ERROR_CODE;
        *p_data_type_out = DATAPOOL_DATATYPE_ERRORCODE;
        *p_data_size_out = sizeof(ErrorCode);
        return true;


    /* DP.MISSION.OPMODE */
    case 0xd003:
        *pp_data_out = &DP.MISSION.OPMODE;
        *p_data_type_out = DATAPOOL_DATATYPE_MISSION_OPMODE;
        *p_data_size_out = sizeof(Mission_OpMode);
        return true;


    /* DP.POWER.INITIALISED */
    case 0xd401:
        *pp_data_out = &DP.POWER.INITIALISED;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.POWER.ERROR_CODE */
    case 0xd402:
        *pp_data_out = &DP.POWER.ERROR_CODE;
        *p_data_type_out = DATAPOOL_DATATYPE_ERRORCODE;
        *p_data_size_out = sizeof(ErrorCode);
        return true;


    /* DP.POWER.TIMER_ERROR_CODE */
    case 0xd403:
        *pp_data_out = &DP.POWER.TIMER_ERROR_CODE;
        *p_data_type_out = DATAPOOL_DATATYPE_ERRORCODE;
        *p_data_size_out = sizeof(ErrorCode);
        return true;


    /* DP.POWER.LOW_POWER_MODE_REQUEST */
    case 0xd404:
        *pp_data_out = &DP.POWER.LOW_POWER_MODE_REQUEST;
        *p_data_type_out = DATAPOOL_DATATYPE_BOOL;
        *p_data_size_out = sizeof(bool);
        return true;


    /* DP.POWER.TASK_TIMER_EVENT */
    case 0xd405:
        *pp_data_out = &DP.POWER.TASK_TIMER_EVENT;
        *p_data_type_out = DATAPOOL_DATATYPE_EVENT;
        *p_data_size_out = sizeof(Event);
        return true;


    /* DP.POWER.REQUESTED_OCP_STATE */
    case 0xd406:
        *pp_data_out = &DP.POWER.REQUESTED_OCP_STATE;
        *p_data_type_out = DATAPOOL_DATATYPE_EPS_OCPSTATE;
        *p_data_size_out = sizeof(Eps_OcpState);
        return true;

    
    default:
        DEBUG_ERR("Invalid DP ID: %d", id_in);
        return false;
    }
}

bool DataPool_get_symbol_str(
    DataPool_Id id_in, 
    char **pp_symbol_str_out
) {

    switch (id_in) {
    
    
    /* DP.INITIALISED */
    case 0x0001:
        *pp_symbol_str_out = strdup("DP.INITIALISED");
        return true;


    /* DP.BOARD_INITIALISED */
    case 0x0002:
        *pp_symbol_str_out = strdup("DP.BOARD_INITIALISED");
        return true;


    /* DP.EVENTMANAGER.INITIALISED */
    case 0x0c01:
        *pp_symbol_str_out = strdup("DP.EVENTMANAGER.INITIALISED");
        return true;


    /* DP.EVENTMANAGER.ERROR_CODE */
    case 0x0c02:
        *pp_symbol_str_out = strdup("DP.EVENTMANAGER.ERROR_CODE");
        return true;


    /* DP.EVENTMANAGER.MAX_EVENTS_REACHED */
    case 0x0c03:
        *pp_symbol_str_out = strdup("DP.EVENTMANAGER.MAX_EVENTS_REACHED");
        return true;


    /* DP.EVENTMANAGER.NUM_RAISED_EVENTS */
    case 0x0c04:
        *pp_symbol_str_out = strdup("DP.EVENTMANAGER.NUM_RAISED_EVENTS");
        return true;


    /* DP.EVENTMANAGER.EVENT_LIST_SIZE */
    case 0x0c05:
        *pp_symbol_str_out = strdup("DP.EVENTMANAGER.EVENT_LIST_SIZE");
        return true;


    /* DP.IMU.INITIALISED */
    case 0x9401:
        *pp_symbol_str_out = strdup("DP.IMU.INITIALISED");
        return true;


    /* DP.IMU.ERROR_CODE */
    case 0x9402:
        *pp_symbol_str_out = strdup("DP.IMU.ERROR_CODE");
        return true;


    /* DP.IMU.I2C_ERROR_CODE */
    case 0x9403:
        *pp_symbol_str_out = strdup("DP.IMU.I2C_ERROR_CODE");
        return true;


    /* DP.IMU.STATE */
    case 0x9404:
        *pp_symbol_str_out = strdup("DP.IMU.STATE");
        return true;


    /* DP.IMU.SUBSTATE */
    case 0x9405:
        *pp_symbol_str_out = strdup("DP.IMU.SUBSTATE");
        return true;


    /* DP.IMU.COMMAND */
    case 0x9406:
        *pp_symbol_str_out = strdup("DP.IMU.COMMAND");
        return true;


    /* DP.IMU.GYROSCOPE_DATA */
    case 0x9407:
        *pp_symbol_str_out = strdup("DP.IMU.GYROSCOPE_DATA");
        return true;


    /* DP.IMU.GYROSCOPE_DATA_VALID */
    case 0x9408:
        *pp_symbol_str_out = strdup("DP.IMU.GYROSCOPE_DATA_VALID");
        return true;


    /* DP.IMU.MAGNETOMETER_DATA */
    case 0x9409:
        *pp_symbol_str_out = strdup("DP.IMU.MAGNETOMETER_DATA");
        return true;


    /* DP.IMU.MAGNE_SENSE_ADJUST_DATA */
    case 0x940a:
        *pp_symbol_str_out = strdup("DP.IMU.MAGNE_SENSE_ADJUST_DATA");
        return true;


    /* DP.IMU.MAGNETOMETER_DATA_VALID */
    case 0x940b:
        *pp_symbol_str_out = strdup("DP.IMU.MAGNETOMETER_DATA_VALID");
        return true;


    /* DP.IMU.TEMPERATURE_DATA */
    case 0x940c:
        *pp_symbol_str_out = strdup("DP.IMU.TEMPERATURE_DATA");
        return true;


    /* DP.IMU.TEMPERATURE_DATA_VALID */
    case 0x940d:
        *pp_symbol_str_out = strdup("DP.IMU.TEMPERATURE_DATA_VALID");
        return true;


    /* DP.MEMSTOREMANAGER.ERROR_CODE */
    case 0x1001:
        *pp_symbol_str_out = strdup("DP.MEMSTOREMANAGER.ERROR_CODE");
        return true;


    /* DP.MEMSTOREMANAGER.EEPROM_ERROR_CODE */
    case 0x1002:
        *pp_symbol_str_out = strdup("DP.MEMSTOREMANAGER.EEPROM_ERROR_CODE");
        return true;


    /* DP.MEMSTOREMANAGER.CFG_FILE_1_OK */
    case 0x1003:
        *pp_symbol_str_out = strdup("DP.MEMSTOREMANAGER.CFG_FILE_1_OK");
        return true;


    /* DP.MEMSTOREMANAGER.CFG_FILE_2_OK */
    case 0x1004:
        *pp_symbol_str_out = strdup("DP.MEMSTOREMANAGER.CFG_FILE_2_OK");
        return true;


    /* DP.MEMSTOREMANAGER.CFG_FILE_3_OK */
    case 0x1005:
        *pp_symbol_str_out = strdup("DP.MEMSTOREMANAGER.CFG_FILE_3_OK");
        return true;


    /* DP.EPS.INITIALISED */
    case 0x8801:
        *pp_symbol_str_out = strdup("DP.EPS.INITIALISED");
        return true;


    /* DP.EPS.ERROR_CODE */
    case 0x8802:
        *pp_symbol_str_out = strdup("DP.EPS.ERROR_CODE");
        return true;


    /* DP.EPS.STATE */
    case 0x8803:
        *pp_symbol_str_out = strdup("DP.EPS.STATE");
        return true;


    /* DP.EPS.CONFIG_SYNCED */
    case 0x8804:
        *pp_symbol_str_out = strdup("DP.EPS.CONFIG_SYNCED");
        return true;


    /* DP.EPS.NEW_REQUEST */
    case 0x8805:
        *pp_symbol_str_out = strdup("DP.EPS.NEW_REQUEST");
        return true;


    /* DP.EPS.EPS_REQUEST[EPS_MAX_UART_FRAME_LENGTH] */
    case 0x8806:
        *pp_symbol_str_out = strdup("DP.EPS.EPS_REQUEST[EPS_MAX_UART_FRAME_LENGTH]");
        return true;


    /* DP.EPS.EPS_REQUEST_LENGTH */
    case 0x8807:
        *pp_symbol_str_out = strdup("DP.EPS.EPS_REQUEST_LENGTH");
        return true;


    /* DP.EPS.EPS_REPLY[EPS_MAX_UART_FRAME_LENGTH] */
    case 0x8808:
        *pp_symbol_str_out = strdup("DP.EPS.EPS_REPLY[EPS_MAX_UART_FRAME_LENGTH]");
        return true;


    /* DP.EPS.EPS_REPLY_LENGTH */
    case 0x8809:
        *pp_symbol_str_out = strdup("DP.EPS.EPS_REPLY_LENGTH");
        return true;


    /* DP.EPS.UART_FRAME_NUMBER */
    case 0x880a:
        *pp_symbol_str_out = strdup("DP.EPS.UART_FRAME_NUMBER");
        return true;


    /* DP.EPS.COMMAND_STATUS */
    case 0x880b:
        *pp_symbol_str_out = strdup("DP.EPS.COMMAND_STATUS");
        return true;


    /* DP.EPS.HK_DATA */
    case 0x880c:
        *pp_symbol_str_out = strdup("DP.EPS.HK_DATA");
        return true;


    /* DP.MISSION.INITIALISED */
    case 0xd001:
        *pp_symbol_str_out = strdup("DP.MISSION.INITIALISED");
        return true;


    /* DP.MISSION.ERROR_CODE */
    case 0xd002:
        *pp_symbol_str_out = strdup("DP.MISSION.ERROR_CODE");
        return true;


    /* DP.MISSION.OPMODE */
    case 0xd003:
        *pp_symbol_str_out = strdup("DP.MISSION.OPMODE");
        return true;


    /* DP.POWER.INITIALISED */
    case 0xd401:
        *pp_symbol_str_out = strdup("DP.POWER.INITIALISED");
        return true;


    /* DP.POWER.ERROR_CODE */
    case 0xd402:
        *pp_symbol_str_out = strdup("DP.POWER.ERROR_CODE");
        return true;


    /* DP.POWER.TIMER_ERROR_CODE */
    case 0xd403:
        *pp_symbol_str_out = strdup("DP.POWER.TIMER_ERROR_CODE");
        return true;


    /* DP.POWER.LOW_POWER_MODE_REQUEST */
    case 0xd404:
        *pp_symbol_str_out = strdup("DP.POWER.LOW_POWER_MODE_REQUEST");
        return true;


    /* DP.POWER.TASK_TIMER_EVENT */
    case 0xd405:
        *pp_symbol_str_out = strdup("DP.POWER.TASK_TIMER_EVENT");
        return true;


    /* DP.POWER.REQUESTED_OCP_STATE */
    case 0xd406:
        *pp_symbol_str_out = strdup("DP.POWER.REQUESTED_OCP_STATE");
        return true;


    default:
        DEBUG_ERR("Invalid DP ID: %d", id_in);
        return false;
    }
}
