
/**
 * @ingroup kernel
 * @file Kernel_module_ids.h
 * @author Duncan Hamill (dh2g16@soton.ac.uk/duncanrhamill@googlemail.com)
 * @brief Module IDs for use in reporting constants.
 * 
 * The OBC software uses 16-bit constants in many places, for instance for 
 * DataPool IDs, Event IDs, error codes etc. The concept of a Constant Module 
 * ID is that the first 6 bits of these constants are reserved for a module ID 
 * that identified the module that constant is associated with. For instance 
 * the OBC kernel (main system) is module ID 0 - meaning that an event starting
 * with 0b000000 came from the kernel itself. In a 16-bit unsigned integer this
 * leaves 10 bits available for constants, a total of 1024 different 
 * possibilities. 6 bits of module ID allows for up to 128 modules.
 * 
 * This file defines those IDs for the source code. There is a corresponding
 * document SSS_ConstantModuleIds_v1_20201130.xlsx on the sharepoint which
 * defines these values officially. This file should mirror that file at all
 * times. 
 *
 * Generated by src/system/kernel/Kernel_generate_mod_ids.py
 * 
 * @version 0.1
 * @date 2021-02-15
 * 
 * @copyright Copyright (c) 2020
 */

#ifndef H_KERNEL_MODULE_IDS_H
#define H_KERNEL_MODULE_IDS_H

/* -------------------------------------------------------------------------   
 * INCLUDES
 * ------------------------------------------------------------------------- */

/* Standard library includes */
#include <stdint.h>

/* -------------------------------------------------------------------------   
 * DEFINES
 * ------------------------------------------------------------------------- */

/**
 * @brief The number of bits to left shift the module IDs by.
 *
 * This shift converts a raw ID number into a value which can be ORed against 
 * to generate a full value of, for instance an Event ID.
 * 
 * The module ID for FDIR is 0x02, but it's shifted value is 0x800.
 */
#define KERNEL_MOD_ID_SHIFT (10)

/* -------------------------------------------------------------------------   
 * MODULE IDS
 * ------------------------------------------------------------------------- */


/**
 * @brief Shifted module ID for the Kernel module (System group).
 */
#define MOD_ID_KERNEL ((uint16_t)(0x00<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the DataPool module (System group).
 */
#define MOD_ID_DATAPOOL ((uint16_t)(0x01<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Fdir module (System group).
 */
#define MOD_ID_FDIR ((uint16_t)(0x02<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the EventManager module (System group).
 */
#define MOD_ID_EVENTMANAGER ((uint16_t)(0x03<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the MemStoreManager module (System group).
 */
#define MOD_ID_MEMSTOREMANAGER ((uint16_t)(0x04<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the ParamMonitor module (System group).
 */
#define MOD_ID_PARAMMONITOR ((uint16_t)(0x05<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Scheduler module (System group).
 */
#define MOD_ID_SCHEDULER ((uint16_t)(0x06<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the ServInterface module (System group).
 */
#define MOD_ID_SERVINTERFACE ((uint16_t)(0x07<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the TcProcessor module (System group).
 */
#define MOD_ID_TCPROCESSOR ((uint16_t)(0x08<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Board module (Drivers group).
 */
#define MOD_ID_BOARD ((uint16_t)(0x10<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Delay module (Drivers group).
 */
#define MOD_ID_DELAY ((uint16_t)(0x11<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Eeprom module (Drivers group).
 */
#define MOD_ID_EEPROM ((uint16_t)(0x12<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Gpio module (Drivers group).
 */
#define MOD_ID_GPIO ((uint16_t)(0x13<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the I2c module (Drivers group).
 */
#define MOD_ID_I2C ((uint16_t)(0x14<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Rtc module (Drivers group).
 */
#define MOD_ID_RTC ((uint16_t)(0x15<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Spi module (Drivers group).
 */
#define MOD_ID_SPI ((uint16_t)(0x16<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Timer module (Drivers group).
 */
#define MOD_ID_TIMER ((uint16_t)(0x17<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Uart module (Drivers group).
 */
#define MOD_ID_UART ((uint16_t)(0x18<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Wdt module (Drivers group).
 */
#define MOD_ID_WDT ((uint16_t)(0x19<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Antenna module (Components group).
 */
#define MOD_ID_ANTENNA ((uint16_t)(0x20<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Camera module (Components group).
 */
#define MOD_ID_CAMERA ((uint16_t)(0x21<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Eps module (Components group).
 */
#define MOD_ID_EPS ((uint16_t)(0x22<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Fram module (Components group).
 */
#define MOD_ID_FRAM ((uint16_t)(0x23<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Gnss module (Components group).
 */
#define MOD_ID_GNSS ((uint16_t)(0x24<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Imu module (Components group).
 */
#define MOD_ID_IMU ((uint16_t)(0x25<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Led module (Components group).
 */
#define MOD_ID_LED ((uint16_t)(0x26<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Radio module (Components group).
 */
#define MOD_ID_RADIO ((uint16_t)(0x27<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the Temp module (Components group).
 */
#define MOD_ID_TEMP ((uint16_t)(0x28<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the BeaconApp module (Applications group).
 */
#define MOD_ID_BEACONAPP ((uint16_t)(0x30<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the CameraApp module (Applications group).
 */
#define MOD_ID_CAMERAAPP ((uint16_t)(0x31<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the DeploymentApp module (Applications group).
 */
#define MOD_ID_DEPLOYMENTAPP ((uint16_t)(0x32<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the PayloadApp module (Applications group).
 */
#define MOD_ID_PAYLOADAPP ((uint16_t)(0x33<<KERNEL_MOD_ID_SHIFT))


/**
 * @brief Shifted module ID for the SystemHealthApp module (Applications group).
 */
#define MOD_ID_SYSTEMHEALTHAPP ((uint16_t)(0x34<<KERNEL_MOD_ID_SHIFT))


#endif /* H_KERNEL_MODULE_IDS_H */
