
/**
 * @ingroup kernel
 * @file Kernel_module_ids.h
 * @author Duncan Hamill (dh2g16@soton.ac.uk/duncanrhamill@googlemail.com)
 * @brief App IDs.
 *
 * Generated by src/system/kernel/Kernel_generate_mod_ids.py
 * 
 * @version 4
 * @date 2021-03-10
 * 
 * @copyright Copyright (c) 2020
 */

#ifndef H_KERNEL_APP_IDS_H
#define H_KERNEL_APP_IDS_H

/* -------------------------------------------------------------------------   
 * INCLUDES
 * ------------------------------------------------------------------------- */

/* Internal includes */
#include "system/kernel/Kernel_public.h"

/* -------------------------------------------------------------------------   
 * APP IDS
 * ------------------------------------------------------------------------- */


/**
 * @brief App ID for the Beacon application.
 */
#define APP_ID_BEACON ((Kernel_AppId)(0x30))


/**
 * @brief App ID for the Picture application.
 */
#define APP_ID_PICTURE ((Kernel_AppId)(0x31))


/**
 * @brief App ID for the Deployment application.
 */
#define APP_ID_DEPLOYMENT ((Kernel_AppId)(0x32))


/**
 * @brief App ID for the Payload application.
 */
#define APP_ID_PAYLOAD ((Kernel_AppId)(0x33))


/**
 * @brief App ID for the Mission application.
 */
#define APP_ID_MISSION ((Kernel_AppId)(0x34))


/**
 * @brief App ID for the Power application.
 */
#define APP_ID_POWER ((Kernel_AppId)(0x35))


/**
 * @brief App ID for the Thermal application.
 */
#define APP_ID_THERMAL ((Kernel_AppId)(0x36))


/**
 * @brief App ID for the Comms application.
 */
#define APP_ID_COMMS ((Kernel_AppId)(0x37))


#endif /* H_KERNEL_APP_IDS_H */
